version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/images/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
