run:
  deadline: 20s

  # don't report issues from these dirs
  skip-dirs:
    - vendor
    - assets

  # skip generated files
  skip-files:
  - ".*_fake.go$"
  - "fake_.*.go$"

linters-settings:
  dupl:
    # duplication warning after 400 tokens, increased from 150
    threshold: 400
  revive:
    rules:
    - name: indent-error-flow
      disabled: "true"
    - name: blank-imports
      disabled: "true"
    - name: unexported-return
      disabled: "true"

issues:
  exclude-rules:
  # Exclude some linters from running on tests files.
  - linters:
    - gocyclo
    - dupl
    path: _test\.go
  # Exclude unparam warning for handleError()
  - linters:
    - unparam
    text: "handleError"

linters:
  disable-all: true
  enable:
  - misspell
  - structcheck
  - govet
  - staticcheck
  - deadcode
  - varcheck
  - unparam
  - ineffassign
  - nakedret
  - gocyclo
  - dupl
  - goimports
  - revive
  - gosimple
  - typecheck
  - unused
