name: outside_pr

on:
  pull_request:
    branches: [ main ]
    types: [ labeled ]
    paths-ignore:
    - 'docs/**'
    - 'README.md'

env:
  SETUP_GO_VERSION: '^1.17.2'
  GINKGO_NODES: 8

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.1.1

      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Tools
        run: make tools-install

      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH

      - name: Lint Epinio
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Acceptance tests
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          EPINIO_TIMEOUT_MULTIPLIER: 5
        run: |
          make acceptance-cluster-setup
          export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig
          make install-cert-manager
          make prepare_environment_k3d
          # Run *ALL* test-acceptance-* tests
          make test-acceptance

      - name: Cleanup k3d cluster
        if: always()
        run: make acceptance-cluster-delete

      - name: Clean all
        if: always()
        uses: colpal/actions-clean@v1
