name: RKE-CI

on:
  schedule:
    - cron:  '0 2 * * *'

env:
  SETUP_GO_VERSION: '^1.13.7'
  GINKGO_NODES: 1
  FLAKE_ATTEMPTS: 1

jobs:
  acceptance-scenario7:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get All Git Tags
        run: git fetch --force --prune --unshallow --tags

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/ginkgo@v1.16.2

      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Tools
        run: make tools-install

      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH

      - name: Clean runner
        id: clean-runner
        run: |
          make acceptance-cluster-delete

      - name: Create RKE cluster
        id: create-cluster
        run: |
          curl -sfL https://get.rke2.io | sudo sh -
          sudo sh -c "echo RKE2_KUBECONFIG_MODE=0644 > /etc/sysconfig/rke2-server"
          sudo systemctl enable --now rke2-server

      - name: Installation Acceptance Tests
        env:
          REGEX: Scenario7
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
          make test-acceptance-install

      - name: Delete RKE cluster
        if: ${{ always() }}
        run: |
          sudo sh /usr/local/bin/rke2-uninstall.sh
